# SITE CONFIGURATION
baseurl: "/"
url: "https://frincuandreea.com"

# THEME-SPECIFIC CONFIGURATION
title: Andreea Frincu                                    # site's title
description: "Andreea Frincu blog posts about aem, java, javascript, css and much more."      # used by search engines
avatar: assets/img/mylogo.png                         # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: Welcome to my blog, were I try to share with you from my experience.  # Change Blog header text
header_feature_image: assets/img/pexels/book-coffee.webp
footer_text: andreeafrincu

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for social icons, share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
disqus_shortname:                                       # Your discus shortname for comments
exclude_from_localizations: ["assets"]
github_comments_repository: frincuandreea/blogcomments
# PAGINATION
paginate: 5
paginate_path: /blog/page:num

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed, jekyll-sitemap]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
# To use Facebook Comments, create a Facebook app and fill in the Facebook App ID
fb_comment_id: ""
jekyll_admin:
  hidden_links:
    - posts
    - pages
    - data
    - assets
    - drafts
    - config
  homepage: "pages"
